// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://indausutmlnpojljqhco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImluZGF1c3V0bWxucG9qbGpxaGNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNDA3NzcsImV4cCI6MjA2NzcxNjc3N30.5NQ-cBoQuGzHsASWxgxpJ-5lO4NZGb8I_leDH-zARTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});